#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= j1fpga.o sdio_cfg.o sprd_kp.o modem_entry.o pinmap-j1fpga.o ldo_sleep.o sprd_bl.o regulator_init.o lcd_printf.o
