#define BIT_EIC_EB 0
#define BIT_EIC_RTC_EB 0
#define BIT_EIC_RTCDV5_EB 0
#define ANA_REG_GLB_RTC_RST1 0
#define ANA_REG_GLB_RTC_RST0 0
#define ANA_REG_GLB_RTC_RST2 0
#define BIT_AON_GPIO_EB 0
#define ANA_REG_GLB_DCDC_SLP_CTRL0 0
#define BIT_ANA_EFS_EN 0
#define ANA_REG_GLB_LDO_DCDC_PD 0
#define ANA_REG_GLB_DCDC_CTRL15 0
#define ANA_REG_GLB_DCDC_RF_ADI 0
#define ANA_REG_GLB_DCDC_CON_ADI 0
#define ANA_REG_GLB_LDO_V_CTRL11 0
#define ANA_REG_GLB_LDO_V_CTRL7 0
#define ANA_REG_GLB_LDO_V_CTRL3 0
#define ANA_REG_GLB_LDO_V_CTRL8 0
#define ANA_REG_GLB_LDO_V_CTRL10 0
#define ANA_REG_GLB_LDO_V_CTRL9 0
#define ANA_REG_GLB_LDO_V_CTRL6 0
#define ANA_REG_GLB_LDO_V_CTRL4 0
#define ANA_REG_GLB_LDO_V_CTRL5 0
#define BIT_DCDC_V_CTRL_MODE 0
#define ANA_REG_GLB_MIXED_CTRL0 0
#define ANA_REG_GLB_PWR_SEL 0
#define ANA_REG_GLB_PWR_WR_PROT_VALUE 0
#define BIT_CHGR_PD 0
#define BIT_USB_EB 0
#define BIT_OTG_SOFT_RST 0 
#define BIT_OTG_PHY_SOFT_RST 0
#define BIT_OTG_UTMI_SOFT_RST 0
#define REG_AON_APB_SINDRV_CTRL                    ( CTL_BASE_AON_APB + 0x0018 )
#define BIT_SINDRV_ENA                                    ( BIT(0) )
#define BIT_EFUSE_EB                                             BIT_AON_APB_EFUSE_EB
#define BIT_GPIO_EB                                       BIT_AON_APB_GPIO_EB
#define BIT_ANA_GPIO_EN                                      ( BIT(7) )
#define BIT_ADI_EB                                               BIT_AON_APB_ADI_EB
#define BIT_EFUSE_SOFT_RST                                       BIT_AON_APB_EFUSE_SOFT_RST
#define BIT_ADI_SOFT_RST                                         BIT_AON_APB_ADI_SOFT_RST
#define BIT_UART0_EB                       BIT_AP_APB_UART0_EB
#define SPRD_DSI_BASE                       0x00000000
#define SPRD_ADI_PHYS                       SPRD_ADI_BASE
#define SPRD_EIC_PHYS                     SPRD_EIC_BASE
#define SPRD_SYSCNT_PHYS                    SPRD_SYSCNT_BASE
#define SPRD_UIDEFUSE_PHYS                SPRD_UIDEFUSE_BASE
#define CTL_BASE_PWM			SPRD_PWM_BASE
#define SPRD_GPIO_PHYS			    SPRD_GPIO_BASE
#define SPRD_ANA_GPIO_PHYS		   SPRD_GPIO_PHYS
#define SPRD_AONCKG_PHYS                    SPRD_AONCKG_BASE
#define SPRD_ANA_FPU_PHYS       0x00000000
#define SPRD_USB_BASE           0Xe2500000
#define SPRD_ANA_EIC_PHYS         0x00000000
#define ADC_BASE                0x00000000
#define SPRD_APBCKG_BASE        0x00000000
#define SPRD_GPTIMER0_BASE      0x00000000
#define BIT_PWR_WR_PROT 0
#define SPRD_UART0_PHYS			SPRD_UART0_BASE
#define SPRD_UART1_PHYS			SPRD_UART1_BASE
#define BIT_UART1_EB                    BIT_AP_APB_UART1_EB
