/***************************************************************
*  Copyright 2014 (c) Discretix Technologies Ltd.              *
*  This software is protected by copyright, international      *
*  treaties and various patents. Any copy, reproduction or     *
*  otherwise use of this software must be authorized in a      *
*  license agreement and include this Copyright Notice and any *
*  other notices specified in the license agreement.           *
*  Any redistribution in binary form must be authorized in the *
*  license agreement and include this Copyright Notice and     *
*  any other notices specified in the license agreement and/or *
*  in materials provided with the binary distribution.         *
****************************************************************/



#ifndef _BOOT_IMAGES_VERIFIER_ERROR_H
#define _BOOT_IMAGES_VERIFIER_ERROR_H

#ifdef __cplusplus
extern "C"
{
#endif


#define DX_BOOT_IMG_VERIFIER_INV_INPUT_PARAM                            DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000001
#define DX_BOOT_IMG_VERIFIER_OTP_VERSION_FAILURE                        DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000002
#define DX_BOOT_IMG_VERIFIER_CERT_MAGIC_NUM_INCORRECT                   DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000003
#define DX_BOOT_IMG_VERIFIER_CERT_VERSION_NUM_INCORRECT                 DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000004
#define DX_BOOT_IMG_VERIFIER_SW_VER_SMALLER_THAN_MIN_VER                DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000005
#define DX_BOOT_IMG_VERIFIER_PUB_KEY_HASH_VALIDATION_FAILURE            DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000006
#define DX_BOOT_IMG_VERIFIER_RSA_SIG_VERIFICATION_FAILED                DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000007
#define DX_BOOT_IMG_VERIFIER_WORKSPACE_SIZE_TOO_SMALL                   DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000008
#define DX_BOOT_IMG_VERIFIER_SW_COMP_FAILED_VERIFICATION                DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000009
#define DX_BOOT_IMG_VERIFIER_SECONDARY_N_FAILED_VERIFICATION            DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000A
#define DX_BOOT_IMG_VERIFIER_UNSUPPORTED_HASH_ALGORITHM                 DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000B
#define DX_BOOT_IMG_VERIFIER_UNSUPPORTED_RSA_ALGORITHM                  DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000C
#define DX_BOOT_IMG_VERIFIER_CERT_VER_ID_ILLEGAL		        DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000D
#define DX_BOOT_IMG_VERIFIER_PUB_KEY_VALIDATION_WITH_SAVED_KEY_FAILED   DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000E
#define DX_BOOT_IMG_VERIFIER_HASH_BUF_TOO_SMALL                         DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000000F
#define DX_BOOT_IMG_VERIFIER_SW_COMP_INDEX_TOO_BIG                      DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000010
#define DX_BOOT_IMG_VERIFIER_SW_COMP_SIZE_IS_NULL                       DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000011
#define DX_BOOT_IMG_VERIFIER_PUB_KEY_INDEX_EXCEEDS_LIMITATION           DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000012
#define DX_BOOT_IMG_VERIFIER_EXT_KEY_HASH_VALIDATION_FAILURE            DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000013
#define DX_BOOT_IMG_VERIFIER_PUBLIC_KEY_HASH_EMPTY                      DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000014
#define DX_BOOT_IMG_VERIFIER_ILLEGAL_LCS_FOR_OPERATION_ERR   		DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000015   
#define DX_BOOT_IMG_VERIFIER_PUB_KEY_ALREADY_PROGRAMMED_ERR		DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000016
#define DX_BOOT_IMG_VERIFIER_OTP_WRITE_FAIL_ERR				DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000017
#define DX_BOOT_IMG_VERIFIER_INCORRECT_CERT_TYPE			DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000018
#define DX_BOOT_IMG_VERIFIER_ILLEGAL_HBK_IDX				DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x00000019
#define DX_BOOT_IMG_VERIFIER_PUB_KEY1_NOT_PROGRAMMED_ERR		DX_BOOT_IMG_VERIFIER_BASE_ERROR + 0x0000001A

#ifdef __cplusplus
}
#endif

#endif


