dtb-$(CONFIG_S5PC100) += s5pc1xx-smdkc100.dtb
dtb-$(CONFIG_S5PC110) += s5pc1xx-goni.dtb
dtb-$(CONFIG_EXYNOS4) += exynos4210-origen.dtb \
	exynos4210-smdkv310.dtb \
	exynos4210-universal_c210.dtb \
	exynos4210-trats.dtb \
	exynos4412-trats2.dtb \
	exynos4412-odroid.dtb

dtb-$(CONFIG_EXYNOS5) += exynos5250-arndale.dtb \
	exynos5250-snow.dtb \
	exynos5250-smdk5250.dtb \
	exynos5420-smdk5420.dtb \
	exynos5420-peach-pit.dtb \
	exynos5800-peach-pi.dtb \
	exynos5422-odroidxu3.dtb
dtb-$(CONFIG_TEGRA) += tegra20-harmony.dtb \
	tegra20-medcom-wide.dtb \
	tegra20-paz00.dtb \
	tegra20-plutux.dtb \
	tegra20-seaboard.dtb \
	tegra20-tec.dtb \
	tegra20-trimslice.dtb \
	tegra20-ventana.dtb \
	tegra20-whistler.dtb \
	tegra20-colibri.dtb \
	tegra30-apalis.dtb \
	tegra30-beaver.dtb \
	tegra30-cardhu.dtb \
	tegra30-colibri.dtb \
	tegra30-tec-ng.dtb \
	tegra114-dalmore.dtb \
	tegra124-jetson-tk1.dtb \
	tegra124-nyan-big.dtb \
	tegra124-venice2.dtb
dtb-$(CONFIG_ARCH_UNIPHIER) += \
	uniphier-ph1-sld3-ref.dtb \
	uniphier-ph1-pro4-ref.dtb \
	uniphier-ph1-ld4-ref.dtb \
	uniphier-ph1-sld8-ref.dtb
dtb-$(CONFIG_ARCH_ZYNQ) += zynq-zc702.dtb \
	zynq-zc706.dtb \
	zynq-zed.dtb \
	zynq-zybo.dtb \
	zynq-microzed.dtb \
	zynq-picozed.dtb \
	zynq-zc770-xm010.dtb \
	zynq-zc770-xm012.dtb \
	zynq-zc770-xm013.dtb
dtb-$(CONFIG_AM33XX) += am335x-boneblack.dtb

dtb-$(CONFIG_ARCH_SOCFPGA) +=				\
	socfpga_arria5_socdk.dtb			\
	socfpga_cyclone5_socdk.dtb			\
	socfpga_cyclone5_socrates.dtb
dtb-$(CONFIG_TARGET_STV0991) += stv0991.dtb

dtb-$(CONFIG_LS102XA) += ls1021a-qds.dtb \
	ls1021a-twr.dtb

dtb-$(CONFIG_MACH_SUN4I) += \
	sun4i-a10-a1000.dtb \
	sun4i-a10-ba10-tvbox.dtb \
	sun4i-a10-chuwi-v7-cw0825.dtb \
	sun4i-a10-cubieboard.dtb \
	sun4i-a10-gemei-g9.dtb \
	sun4i-a10-hackberry.dtb \
	sun4i-a10-hyundai-a7hd.dtb \
	sun4i-a10-inet-3f.dtb \
	sun4i-a10-inet-3w.dtb \
	sun4i-a10-inet97fv2.dtb \
	sun4i-a10-jesurun-q5.dtb \
	sun4i-a10-marsboard.dtb \
	sun4i-a10-mini-xplus.dtb \
	sun4i-a10-mk802.dtb \
	sun4i-a10-mk802ii.dtb \
	sun4i-a10-olinuxino-lime.dtb \
	sun4i-a10-pcduino.dtb
dtb-$(CONFIG_MACH_SUN5I) += \
	sun5i-a10s-auxtek-t004.dtb \
	sun5i-a10s-mk802.dtb \
	sun5i-a10s-olinuxino-micro.dtb \
	sun5i-a10s-r7-tv-dongle.dtb \
	sun5i-a13-ampe-a76.dtb \
	sun5i-a13-forfun-q88db.dtb \
	sun5i-a13-hsg-h702.dtb \
	sun5i-a13-inet-86vs.dtb \
	sun5i-a13-olinuxino.dtb \
	sun5i-a13-olinuxino-micro.dtb \
	sun5i-a13-tzx-q8-713b7.dtb \
	sun5i-a13-utoo-p66.dtb
dtb-$(CONFIG_MACH_SUN6I) += \
	sun6i-a31-app4-evb1.dtb \
	sun6i-a31-colombus.dtb \
	sun6i-a31-hummingbird.dtb \
	sun6i-a31-i7.dtb \
	sun6i-a31-m9.dtb \
	sun6i-a31-mele-a1000g-quad.dtb \
	sun6i-a31-mixtile-loftq.dtb \
	sun6i-a31s-cs908.dtb \
	sun6i-a31s-primo81.dtb
dtb-$(CONFIG_MACH_SUN7I) += \
	sun7i-a20-ainol-aw1.dtb \
	sun7i-a20-bananapi.dtb \
	sun7i-a20-bananapro.dtb \
	sun7i-a20-cubieboard2.dtb \
	sun7i-a20-cubietruck.dtb \
	sun7i-a20-hummingbird.dtb \
	sun7i-a20-i12-tvbox.dtb \
	sun7i-a20-m3.dtb \
	sun7i-a20-m5.dtb \
	sun7i-a20-mk808c.dtb \
	sun7i-a20-olinuxino-lime.dtb \
	sun7i-a20-olinuxino-lime2.dtb \
	sun7i-a20-olinuxino-micro.dtb \
	sun7i-a20-orangepi.dtb \
	sun7i-a20-orangepi-mini.dtb \
	sun7i-a20-pcduino3.dtb \
	sun7i-a20-pcduino3-nano.dtb \
	sun7i-a20-primo73.dtb \
	sun7i-a20-wexler-tab7200.dtb \
	sun7i-a20-wits-pro-a20-dkt.dtb \
	sun7i-a20-yones-toptech-bd1078.dtb
dtb-$(CONFIG_MACH_SUN8I_A23) += \
	sun8i-a23-evb.dtb \
	sun8i-a23-ippo-q8h-v5.dtb \
	sun8i-a23-ippo-q8h-v1.2.dtb
dtb-$(CONFIG_MACH_SUN8I_A33) += \
	sun8i-a33-et-q8-v1.6.dtb \
	sun8i-a33-ga10h-v1.1.dtb \
	sun8i-a33-ippo-q8h-v1.2.dtb \
	sun8i-a33-sinlinx-sina33.dtb
dtb-$(CONFIG_MACH_SUN9I) += \
	sun9i-a80-optimus.dtb \
	sun9i-a80-cubieboard4.dtb

dtb-$(CONFIG_VF610) += vf500-colibri.dtb \
	vf610-colibri.dtb

dtb-$(CONFIG_VENDOR_SPRD) += sp9850s-1h10-native.dtb \
	sp9850s-2h10-native.dtb \
	sp9860g-1h10-native.dtb \
	sp9860g-1h10-3g.dtb \
	sp9860g-1h10-3gfhd.dtb \
	sp9860g-1h10-fhdcmcc.dtb \
	sp9860g-1h10-pub0fhd.dtb \
	sp9860g-1h10-al.dtb \
	sp9860g-2h10-native.dtb \
	sp9860g-2h10-domfin.dtb \
	sp9860g-3h10-native.dtb \
	sp9860g-4h10-native.dtb \
	ss_whale2_j7-native.dtb \
	ss_whale2_jigboard-native.dtb \
	sp9850ka_1h10_native.dtb \
	sp9850ka_1h10_go.dtb \
	sp9850ka_2c10_native.dtb \
	sp9850ka_2c20_native.dtb \
	sp9850kh-vdk-smt.dtb \
	sp9850kh-vdk.dtb \
	sp9850kh-fpga.dtb \
	sp9850kh-zebu.dtb \
	sp9850kh-fpga-smt.dtb \
	sp9850ka_2c30_native.dtb \
        sp7731e_fpga.dtb \
	sp7731e_1h10_native.dtb \
	sp7731e_1h20_native.dtb \
	sp7731e_16c10_native.dtb \
        sp9835_haps_native.dtb \
        sp9850kh_1h10.dtb \
	sp9850kh_2c20.dtb \
	pike2_vp.dtb \
	sp9850e_1h10.dtb \
	sp9832e_1h10.dtb \
	sl8541e_1h10.dtb \
	sp9832e_10c20.dtb \
        sp9832e_10c10_32b.dtb \
	sp9832e_1h10_32b.dtb \
	sp9832e_2c10_32b.dtb \
	sp9820e_64b.dtb \
	sp9820e_1h10.dtb \
	sp9820e_13c10.dtb \
	sp9820e_5c10.dtb \
	sp9820e_2c10.dtb \
	sp9820e_1h10_kaios.dtb \
	sp9820e_13c10_kaios.dtb \
	sp9820e_5c10_kaios.dtb \
	sp9820e_2c10_kaios.dtb \
	sp9820e_2h10.dtb \
	sp9820e_17c10.dtb \
	sp9820e_2h10_kaios.dtb \
	sp9832ep_haps.dtb \
	sp9855a_haps.dtb \
	ud710_haps.dtb	\
	ud710_2h10.dtb	\
	ud710_3h10.dtb	\
	ud710_orca_haps.dtb	\
	sp9863a_1h10.dtb \
	sp9863a_10c10.dtb \
	sp9863a_1c10.dtb \
	sp9863a_2h10.dtb \
	sp9863a_3h10.dtb \
	sp9863a_3c10.dtb \
	sp9863a_tsg.dtb \
	ums510_haps.dtb \
	ums312_1h10.dtb \
	ums312_1h10_32b.dtb \
	ums312_2h10.dtb \
	ums312_2h10_32b.dtb \
	ums312_20c10.dtb \
	ums312_3h10_4pro.dtb \
	ums518_zebu.dtb \
	sp9650_haps.dtb \
	udx710_haps.dtb \
	udx710_1h10.dtb \
	udx710_2h10.dtb \
	udx710_3h10.dtb \
	sp9863a_1h10_32b.dtb \
	sp9863a_3h10_32b.dtb \
	sp9863a_3c10_32b.dtb \
	ums518_haps.dtb \
	ums518_haps_bkd.dtb \
	ums512_1h10.dtb \
	ums7520_haps.dtb \
	ums7520_zebu.dtb \
	ums512_20c10.dtb \
	udx710_3h10_32b.dtb

targets += $(dtb-y)

# Add any required device tree compiler flags here
DTC_FLAGS +=

PHONY += dtbs
dtbs: $(addprefix $(obj)/, $(dtb-y))
	@:

clean-files := *.dtb
