#ifdef CONFIG_USB_OTG
obj-y += dwc_otg_driver.o
obj-y += dwc_otg_cil.o
obj-y += dwc_otg_cil_intr.o
obj-y += dwc_otg_pcd_linux.o
obj-y += dwc_otg_pcd.o
obj-y += dwc_otg_pcd_intr.o
obj-y += dwc_common_linux.o
obj-y += sprd_usb2_driver.o
#endif
