#
# Copyright (C) 2015, Intel Corporation
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += start.o sdio_cfg.o sprd_kp.o sp9853i_9c10.o modem_entry.o ldo_sleep.o pinmap-sp9853i.o regulator_init.o sprd_bl.o lcd_printf.o
