
obj-y += dmc_sprd_r2p0.o
obj-y += dmc_sprd_r2p0_bist.o
obj-y += dmc_sprd_misc_r2p0.o
obj-y += lpddr_cfg_r2p0.o
obj-y += ddr_scan_online_sprd_r2p0.o

obj-$(CONFIG_SPRD_DDR_SCAN) += ddr_scan_offline_sprd_r2p0.o

