#
# (C) Copyright 2001-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

#CFLAGS += -DDEBUG

#obj-y += date.o
obj-$(CONFIG_ETB_DUMP) += coresight-etb10.o