obj-y += ../lib/adf_format.o

obj-$(CONFIG_DPU_R2P0) += dpu_r2p0.o
obj-$(CONFIG_DPU_LITE_R1P0) += dpu_lite_r1p0.o
obj-$(CONFIG_DPU_LITE_R2P0) += dpu_lite_r2p0.o
obj-$(CONFIG_DPU_R3P0) += dpu_r3p0.o
obj-$(CONFIG_DPU_R4P0) += dpu_r4p0.o
