/* the head file modifier:     g   2014-12-04 17:30:35*/

/*  
* Copyright (C) 2013 Spreadtrum Communications Inc.  
*
* This program is free software; you can redistribute it and/or  
* modify it under the terms of the GNU General Public License 
* as published by the Free Software Foundation; either version 2 
* of the License, or (at your option) any later version.  
* 
* This program is distributed in the hope that it will be useful, 
* but WITHOUT ANY WARRANTY; without even the implied warranty of 
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  
* GNU General Public License for more details.  
* 
*************************************************  
* Automatically generated C header: do not edit *  
*************************************************  
*/  
#ifndef __H_REGS_DMC_BIST_APB_HEADFILE_H__
#define __H_REGS_DMC_BIST_APB_HEADFILE_H__ 

#define  REGS_DMC_BIST_APB

/* registers definitions for DMC_BIST_APB */
#define REG_DMC_BIST_APB_RF_BIST_CTRL			SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0000)/*DMC_BIST_CTRL*/
#define REG_DMC_BIST_APB_RF_BIST_TRANS_NUM		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0004)/*RF_BIST_TRANS_NUM*/
#define REG_DMC_BIST_APB_RF_BIST_START_ADDR		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0008)/*RF_BIST_START_ADDR*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_MASK		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x000c)/*RF_BIST_DATA_MASK*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_00		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0010)/*RF_BIST_SIPI_DATA_00*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_01		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0014)/*RF_BIST_SIPI_DATA_01*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_02		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0018)/*RF_BIST_SIPI_DATA_02*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_03		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x001c)/*RF_BIST_SIPI_DATA_03*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_04		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0020)/*RF_BIST_SIPI_DATA_04*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_05		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0024)/*RF_BIST_SIPI_DATA_05*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_0	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0028)/*RF_BIST_SIPI_BIT_PATTERN_0*/
#define REG_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_1	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x002c)/*RF_BIST_SIPI_BIT_PATTERN_1*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_00_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0030)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_01_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0034)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_02_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0038)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_03_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x003c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_04_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0040)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_05_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0044)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_06_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0048)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_07_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x004c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_08_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0050)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_09_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0054)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_10_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0058)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_11_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x005c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_12_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0060)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_13_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0064)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_14_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0068)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_15_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x006c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_16_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0070)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_17_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0074)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_18_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0078)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_19_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x007c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_20_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0080)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_21_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0084)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_22_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0088)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_23_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x008c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_24_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0090)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_25_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0094)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_26_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x0098)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_27_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x009c)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_28_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00a0)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_29_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00a4)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_30_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00a8)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_31_PATTERN	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00ac)/*RF_BIST_DATA__PATTERN*/
#define REG_DMC_BIST_APB_RF_BIST_RESULT			SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00b0)/*RF_BIST_RESULT*/
#define REG_DMC_BIST_APB_RF_BIST_FAIL_ADDR		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00b4)/*RF_BIST_FAIL_ADDR*/
#define REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_0		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00b8)/*RF_BIST_FAIL_DATA_0*/
#define REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_1		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00bc)/*RF_BIST_FAIL_DATA_1*/
#define REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_2		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00c0)/*RF_BIST_FAIL_DATA_2*/
#define REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_3		SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00c4)/*RF_BIST_FAIL_DATA_3*/
#define REG_DMC_BIST_APB_RF_LFSR_POLY			SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00c8)/*RF_LFSR_POLY*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L0	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00cc)/*RF_BIST_DATA_LFSR_SEED_L0*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L1	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00d0)/*RF_BIST_DATA_LFSR_SEED_L1*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H0	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00d4)/*RF_BIST_DATA_LFSR_SEED_H0*/
#define REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H1	SCI_ADDR(REGS_DMC_BIST_APB_BASE, 0x00d8)/*RF_BIST_DATA_LFSR_SEED_H1*/



/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_CTRL */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_SIZE(_X_)		((_X_) << 11 & (BIT(11)|BIT(12)))
#define BITS_DMC_BIST_APB_RF_BIST_BURST_LENGTH(_X_)		((_X_) << 7 & (BIT(7)|BIT(8)|BIT(9)|BIT(10)))
#define BITS_DMC_BIST_APB_RF_BIST_DATA_PATTERN_MODE(_X_)	((_X_) << 5 & (BIT(5)|BIT(6)))
#define BITS_DMC_BIST_APB_RF_BIST_MODE(_X_)			((_X_) << 3 & (BIT(3)|BIT(4)))
#define BIT_DMC_BIST_APB_RF_BIST_CLEAR				(BIT(2))
#define BIT_DMC_BIST_APB_RF_BIST_START				(BIT(1))
#define BIT_DMC_BIST_APB_RF_BIST_ENABLE				(BIT(0))

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_TRANS_NUM */
#define BITS_DMC_BIST_APB_RF_BIST_TRANS_NUM(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_START_ADDR */
#define BITS_DMC_BIST_APB_RF_BIST_START_ADDR(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_MASK */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_MASK(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_00 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_00(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_01 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_01(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_02 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_02(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_03 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_03(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_04 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_04(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_DATA_05 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_DATA_05(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)))

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_0 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_0(_X_)	(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_1 */
#define BITS_DMC_BIST_APB_RF_BIST_SIPI_BIT_PATTERN_1(_X_)	(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_00_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_00_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_01_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_01_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_02_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_02_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_03_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_03_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_04_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_04_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_05_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_05_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_06_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_06_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_07_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_07_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_08_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_08_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_09_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_09_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_10_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_10_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_11_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_11_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_12_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_12_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_13_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_13_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_14_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_14_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_15_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_15_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_16_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_16_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_17_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_17_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_18_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_18_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_19_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_19_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_20_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_20_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_21_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_21_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_22_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_22_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_23_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_23_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_24_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_24_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_25_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_25_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_26_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_26_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_27_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_27_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_28_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_28_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_29_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_29_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_30_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_30_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_31_PATTERN */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_31_PATTERN(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_RESULT */
#define BIT_DMC_BIST_APB_RF_BIST_FINISH_FLAG			(BIT(1))
#define BIT_DMC_BIST_APB_RF_BIST_FAIL_FLAG			(BIT(0))

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_FAIL_ADDR */
#define BITS_DMC_BIST_APB_RF_BIST_FAIL_ADDR(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_0 */
#define BITS_DMC_BIST_APB_RF_BIST_FAIL_DATA_0(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_1 */
#define BITS_DMC_BIST_APB_RF_BIST_FAIL_DATA_1(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_2 */
#define BITS_DMC_BIST_APB_RF_BIST_FAIL_DATA_2(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_FAIL_DATA_3 */
#define BITS_DMC_BIST_APB_RF_BIST_FAIL_DATA_3(_X_)		(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_LFSR_POLY */
#define BITS_DMC_BIST_APB_RF_LFSR_POLY_NEG(_X_)			((_X_) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)))
#define BITS_DMC_BIST_APB_RF_LFSR_POLY_POS(_X_)			((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L0 */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L0(_X_)	(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L1 */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_L1(_X_)	(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H0 */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H0(_X_)	(_X_)

/* bits definitions for register REG_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H1 */
#define BITS_DMC_BIST_APB_RF_BIST_DATA_LFSR_SEED_H1(_X_)	(_X_)

#endif
