/* the head file modifier:     g   2014-12-04 15:18:29*/

/*  
* Copyright (C) 2013 Spreadtrum Communications Inc.  
*
* This program is free software; you can redistribute it and/or  
* modify it under the terms of the GNU General Public License 
* as published by the Free Software Foundation; either version 2 
* of the License, or (at your option) any later version.  
* 
* This program is distributed in the hope that it will be useful, 
* but WITHOUT ANY WARRANTY; without even the implied warranty of 
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  
* GNU General Public License for more details.  
* 
*************************************************  
* Automatically generated C header: do not edit *  
*************************************************  
*/  
#ifndef __H_REGS_DJTAG_APB_HEADFILE_H__
#define __H_REGS_DJTAG_APB_HEADFILE_H__ 

#define  REGS_DJTAG_APB

/* registers definitions for DJTAG_APB */
#define REG_DJTAG_APB_DJTAG_IR_LEN			SCI_ADDR(REGS_DJTAG_APB_BASE, 0x000)/*DJTAG_IR_LEN*/
#define REG_DJTAG_APB_DJTAG_DR_LEN			SCI_ADDR(REGS_DJTAG_APB_BASE, 0x004)/*DJTAG_DR_LEN*/
#define REG_DJTAG_APB_DJTAG_IR				SCI_ADDR(REGS_DJTAG_APB_BASE, 0x008)/*DJTAG_IR*/
#define REG_DJTAG_APB_DJTAG_DR				SCI_ADDR(REGS_DJTAG_APB_BASE, 0x00C)/*DJTAG_DR*/
#define REG_DJTAG_APB_DR_PAUSE_RECOV			SCI_ADDR(REGS_DJTAG_APB_BASE, 0x010)/*DR_PAUSE_RECOV*/
#define REG_DJTAG_APB_DJTAG_RND_EN			SCI_ADDR(REGS_DJTAG_APB_BASE, 0x014)/*DJTAG_RND_EN*/
#define REG_DJTAG_APB_DJTAG_UPD_DR			SCI_ADDR(REGS_DJTAG_APB_BASE, 0x018)/*DJTAG_UPD_DR*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR1	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x01C)/*DJTAG_AUTOSCAN_CHAIN_ADDR1*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR2	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x020)/*DJTAG_AUTOSCAN_CHAIN_ADDR2*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR3	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x024)/*DJTAG_AUTOSCAN_CHAIN_ADDR3*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR4	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x028)/*DJTAG_AUTOSCAN_CHAIN_ADDR4*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR5	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x02C)/*DJTAG_AUTOSCAN_CHAIN_ADDR5*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR6	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x030)/*DJTAG_AUTOSCAN_CHAIN_ADDR6*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR7	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x034)/*DJTAG_AUTOSCAN_CHAIN_ADDR7*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR8	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x038)/*DJTAG_AUTOSCAN_CHAIN_ADDR8*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR9	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x03C)/*DJTAG_AUTOSCAN_CHAIN_ADDR9*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR10	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x040)/*DJTAG_AUTOSCAN_CHAIN_ADDR10*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR11	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x044)/*DJTAG_AUTOSCAN_CHAIN_ADDR11*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR12	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x048)/*DJTAG_AUTOSCAN_CHAIN_ADDR12*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR13	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x04C)/*DJTAG_AUTOSCAN_CHAIN_ADDR13*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR14	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x050)/*DJTAG_AUTOSCAN_CHAIN_ADDR14*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR15	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x054)/*DJTAG_AUTOSCAN_CHAIN_ADDR15*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR16	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x058)/*DJTAG_AUTOSCAN_CHAIN_ADDR16*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN1	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x05C)/*DJTAG_AUTOSCAN_CHAIN_PATTERN1*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN2	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x060)/*DJTAG_AUTOSCAN_CHAIN_PATTERN2*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN3	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x064)/*DJTAG_AUTOSCAN_CHAIN_PATTERN3*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN4	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x068)/*DJTAG_AUTOSCAN_CHAIN_PATTERN4*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN5	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x06C)/*DJTAG_AUTOSCAN_CHAIN_PATTERN5*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN6	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x070)/*DJTAG_AUTOSCAN_CHAIN_PATTERN6*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN7	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x074)/*DJTAG_AUTOSCAN_CHAIN_PATTERN7*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN8	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x078)/*DJTAG_AUTOSCAN_CHAIN_PATTERN8*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN9	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x07C)/*DJTAG_AUTOSCAN_CHAIN_PATTERN9*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN10	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x080)/*DJTAG_AUTOSCAN_CHAIN_PATTERN10*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN11	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x084)/*DJTAG_AUTOSCAN_CHAIN_PATTERN11*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN12	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x088)/*DJTAG_AUTOSCAN_CHAIN_PATTERN12*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN13	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x08C)/*DJTAG_AUTOSCAN_CHAIN_PATTERN13*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN14	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x090)/*DJTAG_AUTOSCAN_CHAIN_PATTERN14*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN15	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x094)/*DJTAG_AUTOSCAN_CHAIN_PATTERN15*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN16	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x098)/*DJTAG_AUTOSCAN_CHAIN_PATTERN16*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA1	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x09C)/*DJTAG_AUTOSCAN_CHAIN_DATA1*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA2	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0A0)/*DJTAG_AUTOSCAN_CHAIN_DATA2*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA3	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0A4)/*DJTAG_AUTOSCAN_CHAIN_DATA3*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA4	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0A8)/*DJTAG_AUTOSCAN_CHAIN_DATA4*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA5	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0AC)/*DJTAG_AUTOSCAN_CHAIN_DATA5*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA6	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0B0)/*DJTAG_AUTOSCAN_CHAIN_DATA6*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA7	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0B4)/*DJTAG_AUTOSCAN_CHAIN_DATA7*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA8	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0B8)/*DJTAG_AUTOSCAN_CHAIN_DATA8*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA9	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0BC)/*DJTAG_AUTOSCAN_CHAIN_DATA9*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA10	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0C0)/*DJTAG_AUTOSCAN_CHAIN_DATA10*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA11	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0C4)/*DJTAG_AUTOSCAN_CHAIN_DATA11*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA12	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0C8)/*DJTAG_AUTOSCAN_CHAIN_DATA12*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA13	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0CC)/*DJTAG_AUTOSCAN_CHAIN_DATA13*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA14	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0D0)/*DJTAG_AUTOSCAN_CHAIN_DATA14*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA15	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0D4)/*DJTAG_AUTOSCAN_CHAIN_DATA15*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA16	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0D8)/*DJTAG_AUTOSCAN_CHAIN_DATA16*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK1	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0DC)/*DJTAG_AUTOSCAN_CHAIN_MASK1*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK2	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0E0)/*DJTAG_AUTOSCAN_CHAIN_MASK2*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK3	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0E4)/*DJTAG_AUTOSCAN_CHAIN_MASK3*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK4	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0E8)/*DJTAG_AUTOSCAN_CHAIN_MASK4*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK5	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0EC)/*DJTAG_AUTOSCAN_CHAIN_MASK5*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK6	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0F0)/*DJTAG_AUTOSCAN_CHAIN_MASK6*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK7	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0F4)/*DJTAG_AUTOSCAN_CHAIN_MASK7*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK8	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0F8)/*DJTAG_AUTOSCAN_CHAIN_MASK8*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK9	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x0FC)/*DJTAG_AUTOSCAN_CHAIN_MASK9*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK10	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x100)/*DJTAG_AUTOSCAN_CHAIN_MASK10*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK11	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x104)/*DJTAG_AUTOSCAN_CHAIN_MASK11*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK12	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x108)/*DJTAG_AUTOSCAN_CHAIN_MASK12*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK13	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x10C)/*DJTAG_AUTOSCAN_CHAIN_MASK13*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK14	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x110)/*DJTAG_AUTOSCAN_CHAIN_MASK14*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK15	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x114)/*DJTAG_AUTOSCAN_CHAIN_MASK15*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK16	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x118)/*DJTAG_AUTOSCAN_CHAIN_MASK16*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_SCAN_EN		SCI_ADDR(REGS_DJTAG_APB_BASE, 0x11C)/*DJTAG_AUTOSCAN_SCAN_EN*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_RAW		SCI_ADDR(REGS_DJTAG_APB_BASE, 0x120)/*DJTAG_AUTOSCAN_INT_RAW*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_MASK		SCI_ADDR(REGS_DJTAG_APB_BASE, 0x124)/*DJTAG_AUTOSCAN_INT_MASK*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_EN		SCI_ADDR(REGS_DJTAG_APB_BASE, 0x128)/*DJTAG_AUTOSCAN_INT_EN*/
#define REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_CLR		SCI_ADDR(REGS_DJTAG_APB_BASE, 0x12C)/*DJTAG_AUTOSCAN_INT_CLR*/
#define REG_DJTAG_APB_DJTAG_DAP_MUX_CTRL_SOFT_RST	SCI_ADDR(REGS_DJTAG_APB_BASE, 0x130)/*DJTAG_DAP_MUX_CTRL_SOFT_RST*/



/* bits definitions for register REG_DJTAG_APB_DJTAG_IR_LEN */
#define BITS_DJTAG_APB_DJTAG_IR_LEN(_X_)			((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_DR_LEN */
#define BITS_DJTAG_APB_DJTAG_DR_LEN(_X_)			((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_IR */
#define BITS_DJTAG_APB_DJTAG_IR(_X_)				(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_DR */
#define BITS_DJTAG_APB_DJTAG_DR(_X_)				(_X_)

/* bits definitions for register REG_DJTAG_APB_DR_PAUSE_RECOV */
#define BIT_DJTAG_APB_DJTAG_DR_PAUSE_RECOV			(BIT(0))

/* bits definitions for register REG_DJTAG_APB_DJTAG_RND_EN */
#define BIT_DJTAG_APB_DJTAG_RND_EN				(BIT(0))

/* bits definitions for register REG_DJTAG_APB_DJTAG_UPD_DR */
#define BITS_DJTAG_APB_DJTAG_UPD_DR(_X_)			(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR1 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR1(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR2 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR2(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR3 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR3(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR4 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR4(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR5 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR5(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR6 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR6(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR7 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR7(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR8 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR8(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR9 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR9(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR10 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR10(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR11 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR11(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR12 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR12(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR13 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR13(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR14 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR14(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR15 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR15(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR16 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_ADDR16(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN1 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN1(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN2 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN2(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN3 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN3(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN4 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN4(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN5 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN5(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN6 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN6(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN7 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN7(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN8 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN8(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN9 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN9(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN10 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN10(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN11 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN11(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN12 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN12(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN13 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN13(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN14 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN14(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN15 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN15(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN16 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_PATTERN16(_X_)	(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA1 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA1(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA2 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA2(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA3 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA3(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA4 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA4(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA5 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA5(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA6 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA6(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA7 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA7(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA8 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA8(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA9 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA9(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA10 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA10(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA11 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA11(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA12 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA12(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA13 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA13(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA14 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA14(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA15 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA15(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA16 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_DATA16(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK1 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK1(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK2 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK2(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK3 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK3(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK4 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK4(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK5 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK5(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK6 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK6(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK7 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK7(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK8 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK8(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK9 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK9(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK10 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK10(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK11 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK11(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK12 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK12(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK13 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK13(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK14 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK14(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK15 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK15(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK16 */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_CHAIN_MASK16(_X_)		(_X_)

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_SCAN_EN */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_SCAN_EN(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_RAW */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_INT_RAW(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_MASK */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_INT_MASK(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_EN */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_INT_EN(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_AUTOSCAN_INT_CLR */
#define BITS_DJTAG_APB_DJTAG_AUTOSCAN_INT_CLR(_X_)		((_X_) & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)))

/* bits definitions for register REG_DJTAG_APB_DJTAG_DAP_MUX_CTRL_SOFT_RST */
#define BIT_DJTAG_APB_DJTAG_DAP_MUX_CTRL_SOFT_RST		(BIT(0))

#endif
