#
# Copyright (C) 2015, Intel Corporation
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += start.o sdio_cfg.o sprd_kp.o sp9861e_2h10_2705.o sprd_bl.o modem_entry.o regulator_init.o ldo_sleep.o pinmap-sp9861e_2h10_2705.o pinmap-sp9861e_2h10_2705_a0chip.o lcd_printf.o
