obj-y += ddrc_r1p1.o  ddrc_r1p1_common.o ddrc_r1p1_ctrl_init.o ddrc_r1p1_lpddrx.o ddrc_r1p1_phy_cfg.o ddrc_r1p1_phy_init.o bist.o ddrc_r1p1_auto_detect.o \
    serial.o \
    ddrc_r1p1_br_debug.o

obj-$(CONFIG_DDR_SCAN_BUILD) += ddr_scan_offline.o
