/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 * updated at 2018-12-06 15:47:51
 *
 */

#ifndef RFTI_APB_REG_H
#define RFTI_APB_REG_H

#define CTL_BASE_RFTI_APB_REG 0x32460000

#define REG_RFTI_APB_REG_CFG_RFSPI_EN                      ( CTL_BASE_RFTI_APB_REG + 0x002C )
#define REG_RFTI_APB_REG_RFTI_SPI_CTRL                     ( CTL_BASE_RFTI_APB_REG + 0x0030 )
#define REG_RFTI_APB_REG_LVDSRF_PHY_RX_SET                 ( CTL_BASE_RFTI_APB_REG + 0x0034 )
#define REG_RFTI_APB_REG_LVDSRF_PHY_TX_SET                 ( CTL_BASE_RFTI_APB_REG + 0x0038 )
#define REG_RFTI_APB_REG_LVDSRF_CLK_EN                     ( CTL_BASE_RFTI_APB_REG + 0x003C )
#define REG_RFTI_APB_REG_LVDSRF_RFTI_SOFT_RST              ( CTL_BASE_RFTI_APB_REG + 0x0040 )
#define REG_RFTI_APB_REG_LVDSRF_FS_BIST                    ( CTL_BASE_RFTI_APB_REG + 0x0050 )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_0               ( CTL_BASE_RFTI_APB_REG + 0x0054 )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_1               ( CTL_BASE_RFTI_APB_REG + 0x0058 )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_2               ( CTL_BASE_RFTI_APB_REG + 0x005C )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_3               ( CTL_BASE_RFTI_APB_REG + 0x0060 )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_4               ( CTL_BASE_RFTI_APB_REG + 0x0064 )
#define REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_5               ( CTL_BASE_RFTI_APB_REG + 0x0068 )
#define REG_RFTI_APB_REG_LVDSRF_PHASE_BIST_EN              ( CTL_BASE_RFTI_APB_REG + 0x006C )
#define REG_RFTI_APB_REG_PHASE_CFG_VALUE                   ( CTL_BASE_RFTI_APB_REG + 0x0070 )
#define REG_RFTI_APB_REG_PHASE0_BIST_CTRL                  ( CTL_BASE_RFTI_APB_REG + 0x0074 )
#define REG_RFTI_APB_REG_PHASE1_BIST_CTRL                  ( CTL_BASE_RFTI_APB_REG + 0x0078 )
#define REG_RFTI_APB_REG_BIST_FAIL_CNT0                    ( CTL_BASE_RFTI_APB_REG + 0x007C )
#define REG_RFTI_APB_REG_BIST_FAIL_CNT1                    ( CTL_BASE_RFTI_APB_REG + 0x0080 )
#define REG_RFTI_APB_REG_PRBS_CTRL                         ( CTL_BASE_RFTI_APB_REG + 0x0084 )
#define REG_RFTI_APB_REG_CLKSEL_OVR                        ( CTL_BASE_RFTI_APB_REG + 0x0088 )
#define REG_RFTI_APB_REG_LVDSRF_TEST_CTRL                  ( CTL_BASE_RFTI_APB_REG + 0x008C )
#define REG_RFTI_APB_REG_BIST2_CNTR                        ( CTL_BASE_RFTI_APB_REG + 0x0090 )
#define REG_RFTI_APB_REG_DL_AFIFO_INFO0                    ( CTL_BASE_RFTI_APB_REG + 0x0094 )
#define REG_RFTI_APB_REG_DL_AFIFO_INFO1                    ( CTL_BASE_RFTI_APB_REG + 0x0098 )
#define REG_RFTI_APB_REG_TEST_BUS                          ( CTL_BASE_RFTI_APB_REG + 0x009C )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FS_BIST              ( CTL_BASE_RFTI_APB_REG + 0x00A0 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_0         ( CTL_BASE_RFTI_APB_REG + 0x00A4 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_1         ( CTL_BASE_RFTI_APB_REG + 0x00A8 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_2         ( CTL_BASE_RFTI_APB_REG + 0x00AC )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_3         ( CTL_BASE_RFTI_APB_REG + 0x00B0 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_4         ( CTL_BASE_RFTI_APB_REG + 0x00B4 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_5         ( CTL_BASE_RFTI_APB_REG + 0x00B8 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_RFTI2_PHASE_BIST_EN  ( CTL_BASE_RFTI_APB_REG + 0x00BC )
#define REG_RFTI_APB_REG_RFTI2_PHASE_CFG_VALUE             ( CTL_BASE_RFTI_APB_REG + 0x00C0 )
#define REG_RFTI_APB_REG_RFTI2_PHASE0_BIST_CTRL            ( CTL_BASE_RFTI_APB_REG + 0x00C4 )
#define REG_RFTI_APB_REG_RFTI2_PHASE1_BIST_CTRL            ( CTL_BASE_RFTI_APB_REG + 0x00C8 )
#define REG_RFTI_APB_REG_RFTI2_BIST_FAIL0                  ( CTL_BASE_RFTI_APB_REG + 0x00CC )
#define REG_RFTI_APB_REG_RFTI2_BIST_FAIL1                  ( CTL_BASE_RFTI_APB_REG + 0x00D0 )
#define REG_RFTI_APB_REG_RFTI2_PRBS_CTRL                   ( CTL_BASE_RFTI_APB_REG + 0x00D4 )
#define REG_RFTI_APB_REG_RFTI2_CLKSEL_OVR                  ( CTL_BASE_RFTI_APB_REG + 0x00D8 )
#define REG_RFTI_APB_REG_RFTI2_LVDSRF_TEST_CTRL            ( CTL_BASE_RFTI_APB_REG + 0x00DC )
#define REG_RFTI_APB_REG_RFTI2_BIST2_CNTR                  ( CTL_BASE_RFTI_APB_REG + 0x00E0 )
#define REG_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO0              ( CTL_BASE_RFTI_APB_REG + 0x00E4 )
#define REG_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO1              ( CTL_BASE_RFTI_APB_REG + 0x00E8 )
#define REG_RFTI_APB_REG_RFTI2_TEST_BUS                    ( CTL_BASE_RFTI_APB_REG + 0x00EC )
#define REG_RFTI_APB_REG_PAD_RFTI_SPI_SEL                  ( CTL_BASE_RFTI_APB_REG + 0x00F0 )
#define REG_RFTI_APB_REG_RFTI_SYS_MODE_SEL                 ( CTL_BASE_RFTI_APB_REG + 0x00F4 )
#define REG_RFTI_APB_REG_RFTI_SYS_MODES                    ( CTL_BASE_RFTI_APB_REG + 0x00F8 )
#define REG_RFTI_APB_REG_RFSPI_CTRL_RSVD                   ( CTL_BASE_RFTI_APB_REG + 0x00FC )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG0            ( CTL_BASE_RFTI_APB_REG + 0x0200 )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG1            ( CTL_BASE_RFTI_APB_REG + 0x0204 )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG2            ( CTL_BASE_RFTI_APB_REG + 0x0208 )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG0            ( CTL_BASE_RFTI_APB_REG + 0x020C )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG1            ( CTL_BASE_RFTI_APB_REG + 0x0210 )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG2            ( CTL_BASE_RFTI_APB_REG + 0x0214 )
#define REG_RFTI_APB_REG_RFTI_GSSI_1BIT_SLICE_RD_CFG1      ( CTL_BASE_RFTI_APB_REG + 0x0218 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG0            ( CTL_BASE_RFTI_APB_REG + 0x0220 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG1            ( CTL_BASE_RFTI_APB_REG + 0x0224 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG2            ( CTL_BASE_RFTI_APB_REG + 0x0228 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG0            ( CTL_BASE_RFTI_APB_REG + 0x022C )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG1            ( CTL_BASE_RFTI_APB_REG + 0x0230 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG2            ( CTL_BASE_RFTI_APB_REG + 0x0234 )
#define REG_RFTI_APB_REG_RFTI_GSSI_4BIT_SLICE_RD_CFG1      ( CTL_BASE_RFTI_APB_REG + 0x0238 )
#define REG_RFTI_APB_REG_RFTI_SBI_CMD0                     ( CTL_BASE_RFTI_APB_REG + 0x0240 )
#define REG_RFTI_APB_REG_RFTI_SBI_CMD1                     ( CTL_BASE_RFTI_APB_REG + 0x0244 )
#define REG_RFTI_APB_REG_RFTI_SBI_RDATA                    ( CTL_BASE_RFTI_APB_REG + 0x0248 )
#define REG_RFTI_APB_REG_RFTI_SPI_SLV_STATUS               ( CTL_BASE_RFTI_APB_REG + 0x0250 )
#define REG_RFTI_APB_REG_RX_PD_CNT                         ( CTL_BASE_RFTI_APB_REG + 0x0260 )
#define REG_RFTI_APB_REG_RX_RST_CNT                        ( CTL_BASE_RFTI_APB_REG + 0x0264 )
#define REG_RFTI_APB_REG_RX_CLKSEL_CNT                     ( CTL_BASE_RFTI_APB_REG + 0x0268 )
#define REG_RFTI_APB_REG_RX_CLKEN_CNT                      ( CTL_BASE_RFTI_APB_REG + 0x026C )
#define REG_RFTI_APB_REG_TX_PD_CNT                         ( CTL_BASE_RFTI_APB_REG + 0x0270 )
#define REG_RFTI_APB_REG_TX_RST_CNT                        ( CTL_BASE_RFTI_APB_REG + 0x0274 )
#define REG_RFTI_APB_REG_TX_CLKSEL_CNT                     ( CTL_BASE_RFTI_APB_REG + 0x0278 )
#define REG_RFTI_APB_REG_TX_CLKEN_CNT                      ( CTL_BASE_RFTI_APB_REG + 0x027C )
#define REG_RFTI_APB_REG_LVDSPLL_PD_RST_CTRL               ( CTL_BASE_RFTI_APB_REG + 0x0280 )
#define REG_RFTI_APB_REG_RPLL_PD_RST_CTRL                  ( CTL_BASE_RFTI_APB_REG + 0x0284 )
#define REG_RFTI_APB_REG_RX_SEQ_CTRL                       ( CTL_BASE_RFTI_APB_REG + 0x0290 )
#define REG_RFTI_APB_REG_RX_SEQ_CTRL_CNT                   ( CTL_BASE_RFTI_APB_REG + 0x0294 )
#define REG_RFTI_APB_REG_RFTI_HSDL_TIMESTAMP               ( CTL_BASE_RFTI_APB_REG + 0x0300 )
#define REG_RFTI_APB_REG_RFTI_SYS_HSDL_CFG                 ( CTL_BASE_RFTI_APB_REG + 0x0304 )
#define REG_RFTI_APB_REG_RFTI_SYS_EXT_DBG_MODE_SEL         ( CTL_BASE_RFTI_APB_REG + 0x0308 )
#define REG_RFTI_APB_REG_RFTI_FILLER_SEND_CTRL             ( CTL_BASE_RFTI_APB_REG + 0x0310 )
#define REG_RFTI_APB_REG_RFTI_CRC_CTRL                     ( CTL_BASE_RFTI_APB_REG + 0x0314 )
#define REG_RFTI_APB_REG_RFTI_UL_TRANS_CTRL                ( CTL_BASE_RFTI_APB_REG + 0x031C )
#define REG_RFTI_APB_REG_INT_REQ_RFTI_EN                   ( CTL_BASE_RFTI_APB_REG + 0x0320 )
#define REG_RFTI_APB_REG_INT_REQ_RFTI_CLR                  ( CTL_BASE_RFTI_APB_REG + 0x0324 )
#define REG_RFTI_APB_REG_INT_REQ_RFTI_MASK                 ( CTL_BASE_RFTI_APB_REG + 0x0328 )
#define REG_RFTI_APB_REG_INT_REQ_RFTI_SRC                  ( CTL_BASE_RFTI_APB_REG + 0x032C )

/* REG_RFTI_APB_REG_CFG_RFSPI_EN */

#define BIT_RFTI_APB_REG_CFG_RFSPI_EN                     BIT(0)

/* REG_RFTI_APB_REG_RFTI_SPI_CTRL */

#define BIT_RFTI_APB_REG_RFTI_SBI_RST_SOFT                BIT(6)
#define BIT_RFTI_APB_REG_RFTI_PRI_SPI_RESETB_SOFT         BIT(5)
#define BIT_RFTI_APB_REG_RFTI_SPI1_RESETB_SOFT            BIT(4)
#define BIT_RFTI_APB_REG_RFTI_SPI0_RESETB_SOFT            BIT(3)
#define BIT_RFTI_APB_REG_RFTI_PRI_SPI_EN                  BIT(2)
#define BIT_RFTI_APB_REG_RFTI_SPI_MODE                    BIT(1)
#define BIT_RFTI_APB_REG_RFTI_SPI_ARB_ROTATE_EN           BIT(0)

/* REG_RFTI_APB_REG_LVDSRF_PHY_RX_SET */


/* REG_RFTI_APB_REG_LVDSRF_PHY_TX_SET */


/* REG_RFTI_APB_REG_LVDSRF_CLK_EN */

#define BIT_RFTI_APB_REG_RFTI_CLK_LTH_EN                  BIT(1)

/* REG_RFTI_APB_REG_LVDSRF_RFTI_SOFT_RST */

#define BIT_RFTI_APB_REG_RST_RFTI_LTH_SOFT                BIT(2)
#define BIT_RFTI_APB_REG_RFTI2_RESETB_SOFT                BIT(1)
#define BIT_RFTI_APB_REG_RFTI1_RESETB_SOFT                BIT(0)

/* REG_RFTI_APB_REG_LVDSRF_FS_BIST */

#define BIT_RFTI_APB_REG_RFTI1_FSBIST_TX_FORCE_EN         BIT(7)
#define BIT_RFTI_APB_REG_RFTI1_LVDSPATTERN_FIX_EN         BIT(6)
#define BIT_RFTI_APB_REG_RFTI1_BIST_FAIL1                 BIT(5)
#define BIT_RFTI_APB_REG_RFTI1_BIST_DO1                   BIT(4)
#define BIT_RFTI_APB_REG_RFTI1_FSBIST_EN1                 BIT(3)
#define BIT_RFTI_APB_REG_RFTI1_BIST_FAIL0                 BIT(2)
#define BIT_RFTI_APB_REG_RFTI1_BIST_DO0                   BIT(1)
#define BIT_RFTI_APB_REG_RFTI1_FSBIST_EN0                 BIT(0)

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_0 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_0(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_1 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_1(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_2 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_2(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_3 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_3(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_4 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_4(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_LVDSRF_FIXPATTERN_5 */

#define BIT_RFTI_APB_REG_RFTI1_LVDS_PATTERN_5(x)          (((x) & 0x3FF))

/* REG_RFTI_APB_REG_LVDSRF_PHASE_BIST_EN */


/* REG_RFTI_APB_REG_PHASE_CFG_VALUE */


/* REG_RFTI_APB_REG_PHASE0_BIST_CTRL */

#define BIT_RFTI_APB_REG_RFTI1_DLHSSBREADY0               BIT(22)
#define BIT_RFTI_APB_REG_RFTI1_DLHSSBDATPHFOUND0          BIT(21)

/* REG_RFTI_APB_REG_PHASE1_BIST_CTRL */

#define BIT_RFTI_APB_REG_RFTI1_DLHSSBREADY1               BIT(22)
#define BIT_RFTI_APB_REG_RFTI1_DLHSSBDATPHFOUND1          BIT(21)

/* REG_RFTI_APB_REG_BIST_FAIL_CNT0 */

#define BIT_RFTI_APB_REG_RFTI1_BIST_FAIL_CNT0(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_BIST_FAIL_CNT1 */

#define BIT_RFTI_APB_REG_RFTI1_BIST_FAIL_CNT1(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_PRBS_CTRL */

#define BIT_RFTI_APB_REG_RFTI1_PRBS_CLIP_EN               BIT(31)
#define BIT_RFTI_APB_REG_RFTI1_PRBS_LENGTH(x)             (((x) & 0x3FF))

/* REG_RFTI_APB_REG_CLKSEL_OVR */

#define BIT_RFTI_APB_REG_RFTI1_TX_CLK_FORCE_ON_LV2        BIT(7)
#define BIT_RFTI_APB_REG_RFTI1_RX_CLK_FORCE_ON_LV2        BIT(6)
#define BIT_RFTI_APB_REG_RFTI1_TX_CLK_FORCE_ON_LV1        BIT(5)
#define BIT_RFTI_APB_REG_RFTI1_RX_CLK_FORCE_ON_LV1        BIT(4)
#define BIT_RFTI_APB_REG_RFTI1_TX_CLKSEL_OVR              BIT(1)
#define BIT_RFTI_APB_REG_RFTI1_RX_CLKSEL_OVR              BIT(0)

/* REG_RFTI_APB_REG_LVDSRF_TEST_CTRL */

#define BIT_RFTI_APB_REG_RFTI1_EXTERNAL_CDR_RX_VALUE(x)   (((x) & 0x3FF) << 20)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_FLAGDEST_ERR(x)      (((x) & 0x1F) << 12)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_FLAG_NOT_RDY         BIT(11)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_FLAG_RATE_ERR        BIT(10)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_ACTIVE               BIT(9)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_LENGTH(x)            (((x) & 0x7) << 6)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_EN                   BIT(5)
#define BIT_RFTI_APB_REG_RFTI1_STANDALONE_TEST_EN         BIT(4)
#define BIT_RFTI_APB_REG_RFTI1_DLRCB_TEST_LANE_SEL        BIT(3)
#define BIT_RFTI_APB_REG_RFTI1_EXTERNAL_CDR_TEST_EN       BIT(0)

/* REG_RFTI_APB_REG_BIST2_CNTR */

#define BIT_RFTI_APB_REG_RFTI1_BIST2_SYM_CNTR(x)          (((x) & 0xFFFF) << 16)
#define BIT_RFTI_APB_REG_RFTI1_BIST2_ERR_CNTR(x)          (((x) & 0xFFFF))

/* REG_RFTI_APB_REG_DL_AFIFO_INFO0 */

#define BIT_RFTI_APB_REG_RFTI1_DL_AFIFO_INFO0(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_DL_AFIFO_INFO1 */

#define BIT_RFTI_APB_REG_RFTI1_DL_AFIFO_INFO1(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_TEST_BUS */

#define BIT_RFTI_APB_REG_RFTI1_TESTBUS16(x)               (((x) & 0xFFFF) << 16)
#define BIT_RFTI_APB_REG_RFTI1_TBUS_MODE                  BIT(8)
#define BIT_RFTI_APB_REG_RFTI1_TBUS_ADDR(x)               (((x) & 0xFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FS_BIST */

#define BIT_RFTI_APB_REG_RFTI2_FSBIST_TX_FORCE_EN         BIT(7)
#define BIT_RFTI_APB_REG_RFTI2_LVDSPATTERN_FIX_EN         BIT(6)
#define BIT_RFTI_APB_REG_RFTI2_BIST_FAIL1                 BIT(5)
#define BIT_RFTI_APB_REG_RFTI2_BIST_DO1                   BIT(4)
#define BIT_RFTI_APB_REG_RFTI2_FSBIST_EN1                 BIT(3)
#define BIT_RFTI_APB_REG_RFTI2_BIST_FAIL0                 BIT(2)
#define BIT_RFTI_APB_REG_RFTI2_BIST_DO0                   BIT(1)
#define BIT_RFTI_APB_REG_RFTI2_FSBIST_EN0                 BIT(0)

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_0 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_0(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_1 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_1(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_2 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_2(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_3 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_3(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_4 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_4(x)          (((x) & 0x3FFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_FIXPATTERN_5 */

#define BIT_RFTI_APB_REG_RFTI2_LVDS_PATTERN_5(x)          (((x) & 0x3FF))

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_RFTI2_PHASE_BIST_EN */


/* REG_RFTI_APB_REG_RFTI2_PHASE_CFG_VALUE */


/* REG_RFTI_APB_REG_RFTI2_PHASE0_BIST_CTRL */

#define BIT_RFTI_APB_REG_RFTI2_DLHSSBREADY0               BIT(22)
#define BIT_RFTI_APB_REG_RFTI2_DLHSSBDATPHFOUND0          BIT(21)

/* REG_RFTI_APB_REG_RFTI2_PHASE1_BIST_CTRL */

#define BIT_RFTI_APB_REG_RFTI2_DLHSSBREADY1               BIT(22)
#define BIT_RFTI_APB_REG_RFTI2_DLHSSBDATPHFOUND1          BIT(21)

/* REG_RFTI_APB_REG_RFTI2_BIST_FAIL0 */

#define BIT_RFTI_APB_REG_RFTI2_BIST_FAIL_CNT0(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_BIST_FAIL1 */

#define BIT_RFTI_APB_REG_RFTI2_BIST_FAIL_CNT1(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_PRBS_CTRL */

#define BIT_RFTI_APB_REG_RFTI2_PRBS_CLIP_EN               BIT(31)
#define BIT_RFTI_APB_REG_RFTI2_PRBS_LENGTH(x)             (((x) & 0x3FF))

/* REG_RFTI_APB_REG_RFTI2_CLKSEL_OVR */

#define BIT_RFTI_APB_REG_RFTI2_TX_CLK_FORCE_ON_LV2        BIT(7)
#define BIT_RFTI_APB_REG_RFTI2_RX_CLK_FORCE_ON_LV2        BIT(6)
#define BIT_RFTI_APB_REG_RFTI2_TX_CLK_FORCE_ON_LV1        BIT(5)
#define BIT_RFTI_APB_REG_RFTI2_RX_CLK_FORCE_ON_LV1        BIT(4)
#define BIT_RFTI_APB_REG_RFTI2_TX_CLKSEL_OVR              BIT(1)
#define BIT_RFTI_APB_REG_RFTI2_RX_CLKSEL_OVR              BIT(0)

/* REG_RFTI_APB_REG_RFTI2_LVDSRF_TEST_CTRL */

#define BIT_RFTI_APB_REG_RFTI2_EXTERNAL_CDR_RX_VALUE(x)   (((x) & 0x3FF) << 20)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_FLAGDEST_ERR(x)      (((x) & 0x1F) << 12)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_FLAG_NOT_RDY         BIT(11)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_FLAG_RATE_ERR        BIT(10)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_ACTIVE               BIT(9)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_LENGTH(x)            (((x) & 0x7) << 6)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_EN                   BIT(5)
#define BIT_RFTI_APB_REG_RFTI2_STANDALONE_TEST_EN         BIT(4)
#define BIT_RFTI_APB_REG_RFTI2_DLRCB_TEST_LANE_SEL        BIT(3)
#define BIT_RFTI_APB_REG_RFTI2_EXTERNAL_CDR_TEST_EN       BIT(0)

/* REG_RFTI_APB_REG_RFTI2_BIST2_CNTR */

#define BIT_RFTI_APB_REG_RFTI2_BIST2_SYM_CNTR(x)          (((x) & 0xFFFF) << 16)
#define BIT_RFTI_APB_REG_RFTI2_BIST2_ERR_CNTR(x)          (((x) & 0xFFFF))

/* REG_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO0 */

#define BIT_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO0(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO1 */

#define BIT_RFTI_APB_REG_RFTI2_DL_AFIFO_INFO1(x)          (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI2_TEST_BUS */

#define BIT_RFTI_APB_REG_RFTI2_TESTBUS16(x)               (((x) & 0xFFFF) << 16)
#define BIT_RFTI_APB_REG_RFTI2_TBUS_MODE                  BIT(8)
#define BIT_RFTI_APB_REG_RFTI2_TBUS_ADDR(x)               (((x) & 0xFF))

/* REG_RFTI_APB_REG_PAD_RFTI_SPI_SEL */

#define BIT_RFTI_APB_REG_PAD_RFTI_SPI_SEL(x)              (((x) & 0x3))

/* REG_RFTI_APB_REG_RFTI_SYS_MODE_SEL */

#define BIT_RFTI_APB_REG_RFTI_SYS_DBG_MODE_SEL(x)         (((x) & 0x3))

/* REG_RFTI_APB_REG_RFTI_SYS_MODES */

#define BIT_RFTI_APB_REG_RFTI_SYS_DBG_BUS_TVALUE(x)       (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFSPI_CTRL_RSVD */

#define BIT_RFTI_APB_REG_RFSPI_CTL_RESERVED(x)            (((x) & 0xF) << 1)
#define BIT_RFTI_APB_REG_RFSPI_SLICE_EN                   BIT(0)

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG0 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG0(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG1(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG2 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_WR_CFG2(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG0 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG0(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG1(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG2 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_RD_CFG2(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_1BIT_SLICE_RD_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_1BIT_SLICE_RD_CFG1(x)  (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG0 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG0(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG1(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG2 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_WR_CFG2(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG0 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG0(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG1(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG2 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_RD_CFG2(x)        (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_GSSI_4BIT_SLICE_RD_CFG1 */

#define BIT_RFTI_APB_REG_RFTI_GSSI_4BIT_SLICE_RD_CFG1(x)  (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_SBI_CMD0 */

#define BIT_RFTI_APB_REG_RFTI_SBI_CMD_DATA(x)             (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_SBI_CMD1 */

#define BIT_RFTI_APB_REG_RFTI_SBI_STATE(x)                (((x) & 0xF) << 4)
#define BIT_RFTI_APB_REG_RFTI_SBI_CMD_VLD                 BIT(0)

/* REG_RFTI_APB_REG_RFTI_SBI_RDATA */

#define BIT_RFTI_APB_REG_RFTI_SBI_RDATA(x)                (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_SPI_SLV_STATUS */

#define BIT_RFTI_APB_REG_SPI_SLV2_FIFO_EMPTY              BIT(5)
#define BIT_RFTI_APB_REG_SPI_SLV2_FIFO_FULL               BIT(4)
#define BIT_RFTI_APB_REG_SPI_SLV1_FIFO_EMPTY              BIT(3)
#define BIT_RFTI_APB_REG_SPI_SLV1_FIFO_FULL               BIT(2)
#define BIT_RFTI_APB_REG_SPI_SLV0_FIFO_EMPTY              BIT(1)
#define BIT_RFTI_APB_REG_SPI_SLV0_FIFO_FULL               BIT(0)

/* REG_RFTI_APB_REG_RX_PD_CNT */

#define BIT_RFTI_APB_REG_RX_PD_CNT(x)                     (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RX_RST_CNT */

#define BIT_RFTI_APB_REG_RX_RST_CNT(x)                    (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RX_CLKSEL_CNT */

#define BIT_RFTI_APB_REG_RX_CLKSEL_CNT(x)                 (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RX_CLKEN_CNT */

#define BIT_RFTI_APB_REG_RX_CLKEN_CNT(x)                  (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_TX_PD_CNT */

#define BIT_RFTI_APB_REG_TX_PD_CNT(x)                     (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_TX_RST_CNT */

#define BIT_RFTI_APB_REG_TX_RST_CNT(x)                    (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_TX_CLKSEL_CNT */

#define BIT_RFTI_APB_REG_TX_CLKSEL_CNT(x)                 (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_TX_CLKEN_CNT */

#define BIT_RFTI_APB_REG_TX_CLKEN_CNT(x)                  (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_LVDSPLL_PD_RST_CTRL */

#define BIT_RFTI_APB_REG_LVDSPLL_PD_CNT(x)                (((x) & 0xFF) << 8)
#define BIT_RFTI_APB_REG_LVDSPLL_RST_CNT(x)               (((x) & 0xFF))

/* REG_RFTI_APB_REG_RPLL_PD_RST_CTRL */

#define BIT_RFTI_APB_REG_RPLL_PD_CNT(x)                   (((x) & 0xFF) << 8)
#define BIT_RFTI_APB_REG_RPLL_RST_CNT(x)                  (((x) & 0xFF))

/* REG_RFTI_APB_REG_RX_SEQ_CTRL */

#define BIT_RFTI_APB_REG_SYNC_FOUND_CTRL_EN               BIT(1)
#define BIT_RFTI_APB_REG_PHASE_FOUND_CTRL_EN              BIT(0)

/* REG_RFTI_APB_REG_RX_SEQ_CTRL_CNT */

#define BIT_RFTI_APB_REG_SYNC_FOUND_CTRL_CNT(x)           (((x) & 0xFFFF) << 16)
#define BIT_RFTI_APB_REG_PHASE_FOUND_CTRL_CNT(x)          (((x) & 0xFFFF))

/* REG_RFTI_APB_REG_RFTI_HSDL_TIMESTAMP */

#define BIT_RFTI_APB_REG_RFTI_HSDL_TIMESTAMP(x)           (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_SYS_HSDL_CFG */

#define BIT_RFTI_APB_REG_RFTI_SYS_HSDL_CFG(x)             (((x) & 0xFFFFFFFF))

/* REG_RFTI_APB_REG_RFTI_SYS_EXT_DBG_MODE_SEL */

#define BIT_RFTI_APB_REG_RFTI_SYS_EXT_DBG_MODE_SEL(x)     (((x) & 0xFF))

/* REG_RFTI_APB_REG_RFTI_FILLER_SEND_CTRL */

#define BIT_RFTI_APB_REG_RFTI_FILLER_SEND_EN              BIT(8)
#define BIT_RFTI_APB_REG_RFTI_FILLER_SEND_NUM(x)          (((x) & 0xFF))

/* REG_RFTI_APB_REG_RFTI_CRC_CTRL */

#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_CNT3(x)             (((x) & 0xF) << 20)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_CNT2(x)             (((x) & 0xF) << 16)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_CNT1(x)             (((x) & 0xF) << 12)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_CNT0(x)             (((x) & 0xF) << 8)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_FLAG3               BIT(7)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_FLAG2               BIT(6)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_FLAG1               BIT(5)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_FLAG0               BIT(4)
#define BIT_RFTI_APB_REG_RFTI_CRC_ERR_CLR                 BIT(1)
#define BIT_RFTI_APB_REG_RFTI_CRC_EN                      BIT(0)

/* REG_RFTI_APB_REG_RFTI_UL_TRANS_CTRL */

#define BIT_RFTI_APB_REG_RFTI_UL_INCESSANT_EN             BIT(0)

/* REG_RFTI_APB_REG_INT_REQ_RFTI_EN */

#define BIT_RFTI_APB_REG_INT_REQ_RFTI_EN(x)               (((x) & 0xFF))

/* REG_RFTI_APB_REG_INT_REQ_RFTI_CLR */

#define BIT_RFTI_APB_REG_INT_REQ_RFTI_CLR(x)              (((x) & 0xFF))

/* REG_RFTI_APB_REG_INT_REQ_RFTI_MASK */

#define BIT_RFTI_APB_REG_INT_REQ_RFTI_MASK(x)             (((x) & 0xFF))

/* REG_RFTI_APB_REG_INT_REQ_RFTI_SRC */

#define BIT_RFTI_APB_REG_INT_REQ_RFTI_SRC(x)              (((x) & 0xFF))

#endif