obj-y += car.o baseia.o dram.o cpu.o sprd_timer.o
obj-$(CONFIG_BASEIA_S3) += resume.o
obj-$(CONFIG_BULLHILL) += bullhill/
obj-$(CONFIG_SPRD_SOC_SP9853I) += sc9853/
obj-$(CONFIG_SOC_IWHALE2) += sc9861/
