#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= sp9863a_1c10.o sdio_cfg.o sprd_kp.o modem_entry.o pinmap-sp9863a.o ldo_sleep.o sprd_bl.o regulator_init.o lcd_printf.o

