subdir-ccflags-y += -I$(src)

obj-y += sprd_main.o sprd_dispc.o sprd_dsi.o sprd_dphy.o sprd_panel.o
obj-$(CONFIG_ROUND_CORNER_SUPPORT) += sprd_round_corner.o

obj-y += dispc/
obj-y += dsi/
obj-y += dphy/
obj-y += lcd/

obj-$(CONFIG_SOC_SHARKLE) += sharkle/
obj-$(CONFIG_SOC_SHARKL3) += sharkl3/
obj-$(CONFIG_SOC_PIKE2) += pike2/
obj-$(CONFIG_SOC_ROC1) += roc1/
obj-$(CONFIG_SOC_SHARKL5) += sharkl5/
obj-$(CONFIG_SOC_SHARKL5PRO) += sharkl5pro/
