obj-y += ddrc_r1p0.o bist.o ddrc_r1p0_common.o ddrc_r1p0_ctrl_init.o ddrc_r1p0_lpddrx.o ddrc_r1p0_phy_cfg.o ddrc_r1p0_phy_init.o \
	ddrc_r1p0_auto_dected.o\
	ddr_scan_offline.o\
	ddr_scan_r1p0.o\
	ddr_test.o
