obj-$(CONFIG_DPHY_SPRD_SHARKLE) += megacores_sharkle.o
obj-$(CONFIG_DPHY_SYNOPSYS_BIDIR_4L) += dwc_mipi_dphy_bidir_4l.o
obj-$(CONFIG_DPHY_INTEL_IP733M) += intel_ip733mdsitop.o
obj-$(CONFIG_DPHY_SPRD_SHARKL5) += megacores_sharkl5.o
obj-$(CONFIG_DPHY_SPRD_ROC1) += megacores_sharkl5.o
obj-$(CONFIG_DPHY_SPRD_SHARKL5PRO) += megacores_sharkl5.o
