#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= ums312_1h10.o sdio_cfg.o sprd_kp.o modem_entry.o pinmap-ums312.o ldo_sleep.o sprd_bl.o regulator_init.o lcd_printf.o sprd_uart_matrix_cfg.o
