#
# Copyright (C) 2015, Intel Corporation
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += start.o sdio_cfg.o sprd_kp.o sp9861e_3h10.o modem_entry.o sprd_bl.o regulator_init.o ldo_sleep.o pinmap-sp9861e_3h10.o lcd_printf.o
